@startuml
interface BeanFactory {
    + getBean(String name) : Object
}

interface SingletonBeanRegistry{
    + getSingleton(String name) : Object
}

class DefaultSingletonBeanRegistry implements SingletonBeanRegistry {
    + getSingleton((String name) : Object
}


@endum